Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
   Enabled: false

Metrics/BlockLength:  
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Enabled: false
